---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: d-etree-1
spec:
  selector:
    matchLabels:
      label: l-p-etree-1
  template: 
    metadata:
      labels:
        label: l-p-etree-1
    spec:
      hostname: p-etree-1
      containers:
      - name: n1
        image: etree-node:v1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8001
        command: ["python3", "node/node.py"]
        env:
        - name: HOSTNAME
          value: "n1"
        - name: PORT
          value: "8001"
        volumeMounts:
        - name: etree
          mountPath: /home/etree
      - name: n2
        image: etree-node:v1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8002
        command: ["python3", "node/node.py"]
        env:
        - name: HOSTNAME
          value: "n2"
        - name: PORT
          value: "8002"
        volumeMounts:
        - name: etree
          mountPath: /home/etree
      - name: n3
        image: etree-node:v1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8003
        command: ["python3", "node/node.py"]
        env:
        - name: HOSTNAME
          value: "n3"
        - name: PORT
          value: "8003"
        volumeMounts:
        - name: etree
          mountPath: /home/etree
      - name: n4
        image: etree-node:v1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8004
        command: ["python3", "node/node.py"]
        env:
        - name: HOSTNAME
          value: "n4"
        - name: PORT
          value: "8004"
        volumeMounts:
        - name: etree
          mountPath: /home/etree
      - name: s1
        image: etree-switch:v1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 10001
        command: ["python3", "switch/switch.py"]
        env:
        - name: HOSTNAME
          value: "s1"
        - name: PORT
          value: "10001"
        volumeMounts:
        - name: etree
          mountPath: /home/etree
      - name: s2
        image: etree-switch:v1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 10002
        command: ["python3", "switch/switch.py"]
        env:
        - name: HOSTNAME
          value: "s2"
        - name: PORT
          value: "10002"
        volumeMounts:
        - name: etree
          mountPath: /home/etree
      - name: s3
        image: etree-switch:v1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 10003
        command: ["python3", "switch/switch.py"]
        env:
        - name: HOSTNAME
          value: "s3"
        - name: PORT
          value: "10003"
        volumeMounts:
        - name: etree
          mountPath: /home/etree
      - name: s4
        image: etree-switch:v1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 10004
        command: ["python3", "switch/switch.py"]
        env:
        - name: HOSTNAME
          value: "s4"
        - name: PORT
          value: "10004"
        volumeMounts:
        - name: etree
          mountPath: /home/etree
      volumes:
      - name: etree
        persistentVolumeClaim:
          claimName: pvc-etree
---
apiVersion: v1
kind: Service
metadata:
  name: s-etree-1
spec:
  selector:
    label: l-p-etree-1
  type: NodePort
  ports:
  - name: n1
    port: 8001
    targetPort: 8001
  - name: n2
    port: 8002
    targetPort: 8002
  - name: n3
    port: 8003
    targetPort: 8003
  - name: n4
    port: 8004
    targetPort: 8004
  - name: s1
    port: 10001
    targetPort: 10001
    nodePort: 32001
  - name: s2
    port: 10002
    targetPort: 10002
    nodePort: 32002
  - name: s3
    port: 10003
    targetPort: 10003
    nodePort: 32003
  - name: s4
    port: 10004
    targetPort: 10004
    nodePort: 32004
