---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-node
  labels:
    pv: pv-node
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /abs/path/to/etree/node
    server: ip.of.the.master
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-node
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
  selector:
    matchLabels:
      pv: pv-node
