---
apiVersion: apps/v1
kind: Deployment # 定义Dep资源
metadata:
  name: d-etree-1 # Dep的名字
spec:
  selector: # 选择对应label的pod参与进去这个Dep
    matchLabels:
      label: l-p-etree-1
  template: # 定义pod 
    metadata:
      labels: # 定义label使得被上面选中
        label: l-p-etree-1
    spec:
      hostname: p-etree-1 # 定义pod的HOSTNAME
      containers: # 定义pod内容器
      - name: n1
        image: etree:v1.0
        imagePullPolicy: Never # 使用本地镜像
        ports:
        - containerPort: 8001
        command: ["python3", "hybrid.py"]
        env:
        - name: HOSTNAME
          value: "n1"
        - name: PORT
          value: "8001"
        volumeMounts:
        - name: etree # 选中一个volume
          mountPath: /home/etree # 挂载到容器目录
      - name:  n2
        image: etree:v1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8002
        command: ["python3", "hybrid.py"]
        env:
        - name: HOSTNAME
          value: "n2"
        - name: PORT
          value: "8002"
        volumeMounts:
        - name: etree
          mountPath: /home/etree
      - name:  n3
        image: etree:v1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8003
        command: ["python3", "hybrid.py"]
        env:
        - name: HOSTNAME
          value: "n3"
        - name: PORT
          value: "8003"
        volumeMounts:
        - name: etree
          mountPath: /home/etree
      - name:  n4
        image: etree:v1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8004
        command: ["python3", "hybrid.py"]
        env:
        - name: HOSTNAME
          value: "n4"
        - name: PORT
          value: "8004"
        volumeMounts:
        - name: etree
          mountPath: /home/etree
      volumes:
      - name: etree # 只能是小写字母和数字
        persistentVolumeClaim:
          claimName: pvc-etree
# 分割多个资源
---
apiVersion: v1
kind: Service
metadata:
  name: s-etree-1
spec:
  selector: # 不需要matchLabels
    label: l-p-etree-1 # 选中pod
  type: NodePort # 将service暴露给外部
  ports:
  - name: n1
    port: 8001 # service监听，供k8s内部访问
    targetPort: 8001 # 转发到pod内容器端口
    nodePort: 30001 # pod内容器监听，供外部访问
  - name: n2
    port: 8002
    targetPort: 8002
    nodePort: 30002
  - name: n3
    port: 8003
    targetPort: 8003
    nodePort: 30003
  - name: n4
    port: 8004
    targetPort: 8004
    nodePort: 30004
